### ISSUE TITLE
Update Sponsors for 2021-2022?

### ISSUE THREAD

**Issue by ElectronicsTinkerer** [cwruRobotics/cwruRobotics.github.io#10]

**Comment by InvincibleRMC** [comment]
CITC, Kyrocera SGS, Makergear, [Mitee bite], M.A. Ford, Altium, Dassault Systèmes, [Schunk], SBG Systems, Case Alumni Association, Think[box]
If I put "[]"s around a company, they have offered to sponsor us, but we have not asked for products yet
